site_name: beer_app
site_description: Beer rating site for aficionados.
repo_url: https://github.com/johan.j.genis@gmail.com/beer_app_rest_api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/johan.j.genis@gmail.com">johan.j.genis@gmail.com</a>.
dev_addr: 0.0.0.0:8002

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
