# Generated by Django 2.1.10 on 2019-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery_location',
            field=models.CharField(default='Some Brewery', max_length=50),
        ),
        migrations.AddField(
            model_name='beer',
            name='calories',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(default='Bitter', max_length=50),
        ),
        migrations.AddField(
            model_name='beer',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
