# Generated by Django 2.1.10 on 2019-07-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190702_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
